# Generated by Django 5.0 on 2023-12-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=70)),
                ('session', models.CharField(max_length=100)),
                ('pips', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=70)),
                ('entry_time', models.CharField(max_length=70)),
                ('comment', models.CharField(max_length=100)),
                ('before_chart', models.CharField(max_length=100)),
                ('after_chart', models.CharField(max_length=70)),
            ],
        ),
    ]
